In [2]:
import numpy as np
import matplotlib.pyplot as plt

<!-- 04:00–06:00 (2 min) -->
## Bloque: porosidad vs profundidad

Objetivo del bloque:

- Línea con `plt.plot`
- Mínimo de comunicación: **título + ejes**
- Customización para claridad: `color`, `linestyle`/`linewidth`, `figsize`


<!-- 06:00–08:00 (2 min) -->
### Datos (provistos)

Contexto: perfil sintético de **porosidad** en función de la **profundidad**.

- La porosidad suele disminuir con profundidad
- Puede haber oscilaciones suaves por cambios de litología

Esta celda genera los datos que usarás.


In [3]:
# Datos geología: porosidad (%) vs profundidad (m)
profundidad_m = np.linspace(0, 3000, 61)

# Porosidad: decrece + oscilación determinista (sin aleatoriedad)
porosidad_pct = 28 * np.exp(-profundidad_m / 1800) + 1.2 * np.sin(profundidad_m / 260)

# Revisión rápida (no es el ejercicio)
profundidad_m[:5], porosidad_pct[:5]


(array([  0.,  50., 100., 150., 200.]),
 array([28.        , 27.46227482, 26.93710831, 26.41578075, 25.89020022]))

### Ejercicio 1.1

Crea un gráfico de línea de `porosidad_pct` vs `profundidad_m`.

Requisitos:

- usa `plt.figure(figsize=(8,4))`
- `plt.plot` con:
  - `color="tab:blue"`
  - `linestyle="--"` **o** `linewidth=2`
- agrega:
  - `plt.title(...)`
  - `plt.xlabel(...)`
  - `plt.ylabel(...)`

In [4]:
# TU CÓDIGO AQUÍ (Ejercicio 1.1)




<!-- 20:00–22:00 (2 min) -->
## Bloque 2: conteos por categoría (barras)

Objetivo del bloque:

- Construir conteos con **diccionario + for**
- Graficar con `plt.bar`
- Customización para legibilidad:
  - `color=...`
  - `alpha=...`
  - `plt.xticks(rotation=...)`


<!-- 22:00–24:00 (2 min) -->
### Datos (provistos)

Encuesta: **canal preferido para coordinar actividades**.

Categorías:

- `"email"`, `"whatsapp"`, `"sms"`, `"llamada"`, `"presencial"`


In [6]:
# Datos sociología: respuestas de una encuesta (categorías)
respuestas = [
    "whatsapp","whatsapp","email","whatsapp","llamada","whatsapp","presencial","whatsapp",
    "sms","whatsapp","email","email","whatsapp","llamada","presencial","whatsapp",
    "sms","whatsapp","email","whatsapp","llamada","whatsapp","presencial","email",
    "whatsapp","sms","whatsapp","email","llamada","whatsapp"
]
len(respuestas)


30

<!-- 24:00–32:00 (8 min) -->
### Ejercicio 2.1 — Contar y graficar (barras)

1) Construye `conteos` usando un `for`:

- si la categoría ya existe: suma 1
- si no existe: inicializa en 1

2) Crea dos listas:

- `categorias` (texto)
- `frecuencias` (números)

3) Grafíca con `plt.bar`. Barras verdes y con ticks rotatdos.


Agrega título y ejes.


In [7]:
# TU CÓDIGO AQUÍ (Ejercicio 2.1)


pass


<!-- 38:00–40:00 (2 min) -->
## Bloque 3: dispersión y distribución

Objetivo del bloque:

- `plt.scatter` para relación entre variables
- Customización: `color`, `marker`, `alpha`, `figsize`
- Luego: `plt.hist` para ver la **distribución** de una variable


<!-- 40:00–42:00 (2 min) -->
### Datos (provistos)

Contexto: ensayo de difusión en agar.

- `concentracion_mgL` (mg/L)
- `diametro_mm` (mm) del halo de inhibición

Datos sintéticos con saturación suave (determinista).


In [9]:
concentracion_mgL = np.linspace(0, 50, 26)

# Respuesta saturante (tipo Michaelis-Menten) + variación determinista suave
diametro_mm = 6 + (18 * concentracion_mgL / (12 + concentracion_mgL)) + 0.6 * np.sin(concentracion_mgL / 6)

concentracion_mgL[:5], diametro_mm[:5]


(array([0., 2., 4., 6., 8.]),
 array([ 6.        ,  8.76774539, 10.87102188, 12.50488259, 13.78316274]))

<!-- 42:00–50:00 (8 min) -->
### Ejercicio 3.1 — Scatter claro

Crea un scatter de `diametro_mm` vs `concentracion_mgL`. Incluye un marcador violeta, un circulo de marcador y opacidad.

Requisitos:

- `plt.figure(figsize=(7,4))`


In [10]:
# TU CÓDIGO AQUÍ (Ejercicio 3.1)

pass


<!-- 53:00–56:00 (3 min) -->
### Ejercicio 3.2 — Histograma (distribución)

Grafíque un histograma de la distribución de  `diametro_mm`, mediante el método `plt.hist`

use:

- `plt.figure(figsize=(7,4))`


In [12]:
# TU CÓDIGO AQUÍ (Ejercicio 3.2)

pass


<!-- 56:00–58:00 (2 min) -->
## Bloque 4: dos series, poca claridad

Objetivo del bloque:

- Partes de un gráfico “funciona, pero no comunica”
- Debes agregar:
  - título + ejes
  - leyenda (hay dos series)
  - al menos **3** customizaciones (de la lista permitida)


<!-- 58:00–60:00 (2 min) -->
### Datos (provistos)

Geología: **velocidad sísmica proxy** vs profundidad en dos sitios (`Sitio A`, `Sitio B`).

Los datos son sintéticos y ligeramente distintos entre sitios.


In [14]:
profundidad3_m = np.linspace(0, 2500, 51)

velocidad_A = 3.2 + 0.00055 * profundidad3_m + 0.10 * np.sin(profundidad3_m / 170)
velocidad_B = 3.0 + 0.00062 * profundidad3_m + 0.08 * np.sin(profundidad3_m / 150) + 0.05 * np.cos(profundidad3_m / 260)

profundidad3_m[:3], velocidad_A[:3], velocidad_B[:3]


(array([  0.,  50., 100.]),
 array([3.2       , 3.25648955, 3.31048938]),
 array([3.05      , 3.10625387, 3.15781672]))

<!-- 60:00–72:00 (12 min) -->
### Ejercicio 4.1 — “Hazlo comunicable”

La siguiente celda dibuja dos curvas, pero es difícil de interpretar.

Tu tarea:

1) Agrega **título** y **etiquetas de ejes**  
2) Agrega `label=...` en cada `plt.plot` y luego `plt.legend()`  
3) Aplica al menos **tres** customizaciones (elige 3 o más):

- `plt.figure(figsize=(..., ...))`
- `color=...`
- `linestyle=...`
- `linewidth=...`
- `marker=...`
- `alpha=...`

Opcional: `plt.grid(True)`

Termina con `plt.show()`.


In [1]:
# TU CÓDIGO AQUÍ (Ejercicio 4.1)


pass


<!-- 78:00–80:00 (2 min) -->
## Bloque 5: subplots para comparar condiciones

Objetivo:

- `fig, ejes = plt.subplots(1, 2, figsize=(...,...))`
- Un panel por condición
- Cada panel con título y ejes
- Al menos una customización por panel (`color` o `marker` o `alpha`)


<!-- 80:00–82:00 (2 min) -->
### Datos (provistos)

Microbiología: dos antibióticos (A y B) con curvas dosis–respuesta (diámetro del halo vs concentración).

Datos sintéticos (deterministas) para comparar forma y saturación.


In [17]:
concentracion2_mgL = np.linspace(0, 60, 31)

halo_A = 7 + (20 * concentracion2_mgL / (10 + concentracion2_mgL)) + 0.4 * np.sin(concentracion2_mgL / 7)
halo_B = 7 + (16 * concentracion2_mgL / (18 + concentracion2_mgL)) + 0.4 * np.sin(concentracion2_mgL / 7)

concentracion2_mgL[:4], halo_A[:4], halo_B[:4]


(array([0., 2., 4., 6.]),
 array([ 7.        , 10.44607047, 12.9306194 , 14.80239015]),
 array([ 7.        ,  8.71273714, 10.12542459, 11.30239015]))

<!-- 82:00–88:00 (6 min) -->
### Ejercicio 5.1 — Subplots (1×2)

Crea una figura con dos paneles:

- Panel izquierdo: antibiótico A
- Panel derecho: antibiótico B

Requisitos:

- `fig, ejes = plt.subplots(1, 2, figsize=(10,4))`
- en cada eje:
  - `plot` **o** `scatter` (elige uno y mantén consistencia)
  - título del panel
  - xlabel/ylabel
  - al menos una customización (`color`, `linestyle`, `marker`, `alpha`, `linewidth`)


In [18]:
# TU CÓDIGO AQUÍ (Ejercicio 5.1)

# fig, ejes = plt.subplots(1, 2, figsize=(10,4))
# ejes[0].... (A)
# ejes[1].... (B)

pass
